[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-args=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"
]

[unstable]
# 启用 build-std 功能（关键！）
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
